"""plant posts

Revision ID: 0155c0c6e84b
Revises: 3772da4ab5d9
Create Date: 2026-09-17 12:08:18.999846

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0155c0c6e84b'
down_revision: str | None = '3772da4ab5d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate again wanted to drop/recreate the FKs on the existing
    # tables (schema-qualified referents look "changed" to it). Untouched.
    op.create_table('plant_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['public.plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_plant_posts_plant_id'), 'plant_posts', ['plant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_plant_posts_plant_id'), table_name='plant_posts', schema='public')
    op.drop_table('plant_posts', schema='public')
    # ### end Alembic commands ###
