"""music cache

Revision ID: 3772da4ab5d9
Revises: 5c870ee1878f
Create Date: 2026-09-17 11:29:50.125533

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3772da4ab5d9'
down_revision: str | None = '5c870ee1878f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate also wanted to drop/recreate the FKs on users/plants/gifts
    # (schema-qualified referents look "changed" to it). Those are untouched.
    op.create_table('music_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('result_ids', sa.JSON(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_music_searches_query'), 'music_searches', ['query'], unique=True, schema='public')
    op.create_table('music_tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('thumb', sa.String(length=500), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_music_tracks_video_id'), 'music_tracks', ['video_id'], unique=True, schema='public')
    op.create_table('music_plays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_music_plays_user_video'),
    schema='public'
    )
    op.create_index(op.f('ix_public_music_plays_last_played_at'), 'music_plays', ['last_played_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_music_plays_user_id'), 'music_plays', ['user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_music_plays_video_id'), 'music_plays', ['video_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_music_plays_video_id'), table_name='music_plays', schema='public')
    op.drop_index(op.f('ix_public_music_plays_user_id'), table_name='music_plays', schema='public')
    op.drop_index(op.f('ix_public_music_plays_last_played_at'), table_name='music_plays', schema='public')
    op.drop_table('music_plays', schema='public')
    op.drop_index(op.f('ix_public_music_tracks_video_id'), table_name='music_tracks', schema='public')
    op.drop_table('music_tracks', schema='public')
    op.drop_index(op.f('ix_public_music_searches_query'), table_name='music_searches', schema='public')
    op.drop_table('music_searches', schema='public')
    # ### end Alembic commands ###
