"""initial migration

Revision ID: 5c870ee1878f
Revises: 
Create Date: 2026-09-16 20:43:47.830433

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5c870ee1878f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('member', 'guest', name='user_kind'), nullable=False),
    sa.Column('zitadel_sub', sa.String(length=64), nullable=True),
    sa.Column('idp_issuer', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guest_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idp_issuer', 'zitadel_sub', name='uq_users_idp_subject'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_guest_expires_at'), 'users', ['guest_expires_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_zitadel_sub'), 'users', ['zitadel_sub'], unique=False, schema='public')
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('gratitude', 'memory', 'hope', 'anger', 'feeling', name='plant_category'), nullable=True),
    sa.Column('species', sa.Enum('peony', 'forget-me-not', 'cherry', 'rose', 'foxglove', 'wisteria', name='plant_species'), nullable=True),
    sa.Column('status', sa.Enum('growing', 'given', 'released', name='plant_status'), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('for_whom_name', sa.String(length=120), nullable=True),
    sa.Column('for_whom_email', sa.String(length=320), nullable=True),
    sa.Column('for_whom_give_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_plants_owner_id'), 'plants', ['owner_id'], unique=False, schema='public')
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sessions_expires_at'), 'sessions', ['expires_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='public')
    op.create_table('gifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('to_name', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('given_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['public.plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_gifts_token'), 'gifts', ['token'], unique=True, schema='public')
    op.create_table('plant_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('planted', 'tended', 'given', name='plant_event_type'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['public.plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_plant_events_plant_id'), 'plant_events', ['plant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_plant_events_plant_id'), table_name='plant_events', schema='public')
    op.drop_table('plant_events', schema='public')
    op.drop_index(op.f('ix_public_gifts_token'), table_name='gifts', schema='public')
    op.drop_table('gifts', schema='public')
    op.drop_index(op.f('ix_public_sessions_user_id'), table_name='sessions', schema='public')
    op.drop_index(op.f('ix_public_sessions_expires_at'), table_name='sessions', schema='public')
    op.drop_table('sessions', schema='public')
    op.drop_index(op.f('ix_public_plants_owner_id'), table_name='plants', schema='public')
    op.drop_table('plants', schema='public')
    op.drop_index(op.f('ix_public_users_zitadel_sub'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_guest_expires_at'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    # Alembic does not drop enum types on its own.
    for enum_name in ("user_kind", "plant_category", "plant_species", "plant_status", "plant_event_type"):
        op.execute(f"DROP TYPE IF EXISTS public.{enum_name}")
    # ### end Alembic commands ###
